databases:
  - name: Dynamite Postgres
    databaseName: dynamite_db
    region: singapore
    plan: free
    user: jack

services:
  - type: web
    name: Keyboard Lesson Manager
    runtime: ruby
    region: singapore
    plan: starter
    buildCommand: "bash setup_database.sh"
    startCommand: "bundle exec ruby manager.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Dynamite Postgres
          property: connectionString
