databases:
  - name: Postgres Render Instance
    databaseName: render_db_chci
    region: singapore
    plan: free
    user: jack

services:
  - type: web
    name: Keyboard Lesson Manager
    runtime: ruby
    region: singapore
    plan: starter
    buildCommand: "bundle install; bash setup_database.sh"
    startCommand: "bundle exec ruby manager.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Postgres Render Instance
          property: connectionString
